# Generated by Django 3.0.7 on 2020-06-27 08:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing', models.CharField(max_length=200)),
                ('listing_id', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('contact_date', models.DateTimeField(blank=True, default=datetime.datetime(2020, 6, 27, 13, 53, 16, 627899))),
                ('user_id', models.IntegerField(blank=True)),
            ],
        ),
    ]
